<?xml version="1.0" encoding="utf-8"?><Database Name="SearchedEngineDataBase" Class="LINQToSQLClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\SearchedEngineDataBase.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Porownywarka.Properties.Settings" SettingsPropertyName="SearchedEngineDataBaseConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="IDCustomer" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="IDListOfProducts" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ListOfProducts" Member="ListOfProducts">
    <Type Name="ListOfProduct">
      <Column Name="IDListOfProducts" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDCustomer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDItem" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDItem" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Condition" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PriceType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[Left]" Member="Left" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Bids Count]" Member="Bids_Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Bidders Count]" Member="Bidders_Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EndingTime" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SearchingParameter" Member="SearchingParameters">
    <Type Name="SearchingParameter">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tittle" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinPrice" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaxPrice" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Distance" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>